#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := agGrow_reporting
COMPONENT_ADD_INCLUDEDIRS := components/bt/include
include $(IDF_PATH)/make/project.mk

